name: smtest
favicon: null
layout_spectrum: 0.11769
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9222e'
    - '#000000'
    - '#b1afaf'
    - '#7b7975'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.3386366097256541
  rhythmicContrast: 0.9000322113279253
purpose: []
